wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
batch_size:
  desc: null
  value: 64
num_keep:
  desc: null
  value: 1024
experience_loop:
  desc: null
  value: 8
experience_replay:
  desc: null
  value: 64
lr_z:
  desc: null
  value: 0.1
beta:
  desc: null
  value: 50
mutation_rate:
  desc: null
  value: 0.01
population_size:
  desc: null
  value: 120
offspring_size:
  desc: null
  value: 70
reinitiation_interval:
  desc: null
  value: 1000
rank_coefficient:
  desc: null
  value: 0.01
num_jobs:
  desc: null
  value: 1
penalty:
  desc: null
  value: prior_kl
valid_only:
  desc: null
  value: true
kl_coefficient:
  desc: null
  value: 0.01
starting_ga_from:
  desc: null
  value: 8000
use_novelty:
  desc: null
  value: false
update_during_ga:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.7.0
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739674249.0
    t:
      1:
      - 1
      - 5
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 49
      - 53
      - 55
      3:
      - 16
      - 17
      - 19
      - 23
      - 37
      4: 3.7.0
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
oracle:
  desc: null
  value: qed
method:
  desc: null
  value: ngs
